install.packages("RODBC", "RMySQL", "dplyr", "tidyr", "stringr", "lubridate")
install.packages("ggplot2", "rgl", "googleVis", "car", "lme4", "caret", "randomForest")
isntall.packages("shiny", "rmarkdown", "xtable", "data.table")
isntall.packages("zoo", "xts", "quantmod")
isntall.packages("Rcpp", "parallel", "XML", "jsonlite", "httr", "Rmpfr")
install.packages("devtools", "testthat", "roxygen2","PolynomF","vimcom")
devtools::install_github("hadley/lineprof")
